package Gui;
import Data.UserFileHandler;
import javax.swing.JOptionPane;
import Utils.Session;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class FeedbackFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FeedbackFrame.class.getName());

    /**
     * Creates new form FeedbackFrame
     */
    BufferedImage bg;
    String gameName;
    String mood;
    public FeedbackFrame(String currentMood, String selectedGameName) {
        mood=currentMood;
        gameName=selectedGameName;
        try{
            bg=ImageIO.read(new File(System.getProperty("user.dir").concat("//images//purple.jpg")));      
        }catch (IOException ex){
            System.getLogger(FeedbackFrame.class.getName()).log(System.Logger.Level.ERROR,(String) null, ex);
        }
               initComponents();
         ImageIcon icon = new ImageIcon(new File("images/mindmate.png").getAbsolutePath());
            
    setIconImage(icon.getImage());
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("IZZA AJMAL");
        // Show game and mood info
        jLabel4.setText(gameName);
        jLabel5.setText(mood);       
        // Disable replay and home until feedback given
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
      // --- PASTE THIS AT THE VERY END OF YOUR FEEDBACKFRAME CONSTRUCTOR ---

// 1. Force the frame's content pane to use BorderLayout
this.getContentPane().setLayout(new java.awt.BorderLayout());

// 2. Remove the panel from wherever NetBeans put it, and lock it to the CENTER
this.getContentPane().remove(FeedbackPanel);
this.getContentPane().add(FeedbackPanel, java.awt.BorderLayout.CENTER);

// 3. Force the layout engine to stretch everything to the edges of the screen
this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
this.invalidate();
this.validate();
this.repaint();
// --------------------------------------------------------------------         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        FeedbackPanel = new javax.swing.JPanel(){
            public void paintComponent (Graphics g){
                super.paintComponent(g);
                g.drawImage(bg, 0, 0,this.getWidth(),this.getHeight(),null);
            }
        };
        FeedbackQuestion = new javax.swing.JLabel();
        Yes = new javax.swing.JButton();
        no = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FeedbackPanel.setLayout(new java.awt.GridBagLayout());

        FeedbackQuestion.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        FeedbackQuestion.setForeground(new java.awt.Color(146, 6, 48));
        FeedbackQuestion.setText("How was your experience?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = -16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(101, 41, 0, 73);
        FeedbackPanel.add(FeedbackQuestion, gridBagConstraints);

        Yes.setBackground(new java.awt.Color(0, 198, 253));
        Yes.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        Yes.setForeground(new java.awt.Color(255, 255, 255));
        Yes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/like.png"))); // NOI18N
        Yes.setText("Yes");
        Yes.addActionListener(this::YesActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 67, 0, 0);
        FeedbackPanel.add(Yes, gridBagConstraints);

        no.setBackground(new java.awt.Color(0, 198, 253));
        no.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        no.setForeground(new java.awt.Color(255, 255, 255));
        no.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/dislike.png"))); // NOI18N
        no.setText("No");
        no.addActionListener(this::noActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        FeedbackPanel.add(no, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Did you Enjoy this game?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 115, 0, 0);
        FeedbackPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/joystick.png"))); // NOI18N
        jLabel2.setText("GAME:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 146, 0, 0);
        FeedbackPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/smile.png"))); // NOI18N
        jLabel3.setText("MOOD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 148, 0, 0);
        FeedbackPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 5, 0, 0);
        FeedbackPanel.add(jLabel4, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/undo (1).png"))); // NOI18N
        jButton1.setText("REPLAY");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 41, 0, 0);
        FeedbackPanel.add(jButton1, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 0);
        FeedbackPanel.add(jLabel5, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/house.png"))); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.ipady = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 75, 0, 0);
        FeedbackPanel.add(jButton2, gridBagConstraints);

        getContentPane().add(FeedbackPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesActionPerformed
     Session.userData.addFeedback("LIKED");
    // Save to history.txt
    UserFileHandler.saveHistory(Session.getCurrentUser(),mood,gameName, "LIKED");
    JOptionPane.showMessageDialog(this,"Thanks for your feedback! 😊","Feedback",JOptionPane.INFORMATION_MESSAGE);
    Yes.setEnabled(false);
    no.setEnabled(false);
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
    }//GEN-LAST:event_YesActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
    Session.userData.addFeedback("DISLIKED");
    // Save to history.txt
    UserFileHandler.saveHistory(Session.getCurrentUser(),mood,gameName,"DISLIKED");
    JOptionPane.showMessageDialog(this,"We will recommend better next time! 🙏","Feedback", JOptionPane.INFORMATION_MESSAGE);
    Yes.setEnabled(false);
    no.setEnabled(false);
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);   
    }//GEN-LAST:event_noActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MoodFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new WelcomeFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FeedbackFrame("CALM","Test Game").setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FeedbackPanel;
    private javax.swing.JLabel FeedbackQuestion;
    private javax.swing.JButton Yes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton no;
    // End of variables declaration//GEN-END:variables

    
}
